// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface AboutUs {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  show_hero?: boolean;
  hero_badge?: string;
  hero_title?: string;
  hero_description?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  hero_primary_label?: string;
  hero_primary_url?: string;
  hero_secondary_label?: string;
  hero_secondary_url?: string;
  show_legacy?: boolean;
  legacy_heading?: string;
  legacy_paragraph_1?: string;
  legacy_paragraph_2?: string;
  stat_1_value?: string;
  stat_1_label?: string;
  stat_2_value?: string;
  stat_2_label?: string;
  legacy_side_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  legacy_badge_icon?: string;
  legacy_badge_text?: string;
  show_mission?: boolean;
  mission_section_title?: string;
  mission_section_subtitle?: string;
  vision_icon?: string;
  vision_title?: string;
  vision_text?: string;
  mission_block_icon?: string;
  mission_block_title?: string;
  mission_block_text?: string;
  show_values?: boolean;
  values_heading?: string;
  core_values?: unknown;
  show_cta?: boolean;
  cta_title?: string;
  cta_description?: string;
  cta_primary_label?: string;
  cta_primary_url?: string;
  cta_secondary_label?: string;
  cta_secondary_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Advisor {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  role_title?: string;
  bio?: PortableTextBlock[];
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  certifications?: string;
  specialties?: ("Retirement Planning" | "Tax Planning" | "Wealth Management" | "Insurance" | "Mutual Funds" | "Stocks" | "Crypto" | "Estate Planning" | "Corporate Finance")[];
  email?: string;
  phone?: string;
  social_links?: unknown;
  is_featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface BookConsultationPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  trust_badge_label?: string;
  intro_title?: string;
  intro_subtitle?: string;
  show_feature_1?: boolean;
  feature_1_icon?: string;
  feature_1_title?: string;
  feature_1_body?: string;
  show_feature_2?: boolean;
  feature_2_icon?: string;
  feature_2_title?: string;
  feature_2_body?: string;
  form_title?: string;
  form_description?: string;
  service_field_label?: string;
  form_time_slot_options?: string;
  form_message_placeholder?: string;
  form_privacy_text?: string;
  form_button_label?: string;
  form_submit_note?: string;
  notification_emails?: string;
  notification_subject?: string;
  show_brand_logos?: boolean;
  brand_logo_1?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  brand_logo_2?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  brand_logo_3?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  brand_logo_4?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface BookConsultationSubmission {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  full_name: string;
  phone?: string;
  email: string;
  service_slug?: string;
  service_name?: string;
  preferred_date?: string;
  preferred_time?: string;
  message?: string;
  privacy_consent?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ContactPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  hero_title?: string;
  hero_subtitle?: string;
  show_phone_card?: boolean;
  phone_card_title?: string;
  phone_card_description?: string;
  phone_number?: string;
  phone_href?: string;
  show_email_card?: boolean;
  email_card_title?: string;
  email_card_description?: string;
  email_address?: string;
  email_href?: string;
  show_line_card?: boolean;
  line_card_title?: string;
  line_card_description?: string;
  line_link_label?: string;
  line_link_href?: string;
  form_title?: string;
  form_description?: string;
  form_subject_options?: string;
  form_privacy_text?: string;
  form_button_label?: string;
  notification_emails?: string;
  notification_subject?: string;
  show_office_details?: boolean;
  office_title?: string;
  office_address_line1?: string;
  office_address_line2?: string;
  show_office_hours?: boolean;
  hours_heading?: string;
  hours_weekday_label?: string;
  hours_weekday_hours?: string;
  hours_saturday_label?: string;
  hours_saturday_hours?: string;
  hours_sunday_label?: string;
  hours_sunday_hours?: string;
  show_map_section?: boolean;
  map_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  map_link_url?: string;
  map_alt?: string;
  show_trust_section?: boolean;
  trust_title?: string;
  trust_text?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ContactFormSubmission {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  full_name: string;
  phone?: string;
  email: string;
  subject?: string;
  message?: string;
  privacy_consent?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface FaqPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  hero_title?: string;
  hero_description?: string;
  search_placeholder?: string;
  categories_heading?: string;
  popular_badge_label?: string;
  sidebar_categories?: unknown;
  show_cta?: boolean;
  cta_title?: string;
  cta_description?: string;
  cta_background_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  cta_primary_label?: string;
  cta_primary_url?: string;
  cta_secondary_label?: string;
  cta_secondary_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  answer?: PortableTextBlock[];
  order?: number;
  is_popular?: boolean;
  is_feature?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Home {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  hero_section_show?: boolean;
  hero_badge?: string;
  hero_headline_line1?: string;
  hero_headline_line2?: string;
  hero_description?: string;
  cta_primary_label?: string;
  cta_primary_url?: string;
  cta_secondary_label?: string;
  cta_secondary_url?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  sec_show?: boolean;
  sec_title?: string;
  sec_description?: string;
  sec_icon?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  trust_1_line1?: string;
  trust_1_line2?: string;
  trust_1_icon?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  trust_2_line1?: string;
  trust_2_line2?: string;
  trust_2_icon?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  trust_3_line1?: string;
  trust_3_line2?: string;
  trust_3_icon?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  trust_4_line1?: string;
  trust_4_line2?: string;
  trust_4_icon?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  services_section_show?: boolean;
  services_section_title?: string;
  services_section_description?: string;
  services_section_link_label?: string;
  services_section_link_href?: string;
  advisors_section_show?: boolean;
  advisors_section_title?: string;
  advisors_section_description?: string;
  advisors_section_link_label?: string;
  advisors_section_link_href?: string;
  knowledge_section_show?: boolean;
  knowledge_section_title?: string;
  knowledge_section_description?: string;
  knowledge_section_link_label?: string;
  knowledge_section_link_href?: string;
  testimonials_section_show?: boolean;
  testimonials_section_title?: string;
  testimonials_section_description?: string;
  faq_section_show?: boolean;
  faq_section_title?: string;
  final_cta_section_show?: boolean;
  final_cta_background_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  final_cta_overlay?: boolean;
  final_cta_background_opacity?: number;
  final_cta_headline_line1?: string;
  final_cta_headline_line2?: string;
  final_cta_description?: string;
  final_cta_primary_label?: string;
  final_cta_primary_url?: string;
  final_cta_secondary_label?: string;
  final_cta_secondary_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface InvestmentArticlesPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  hero_title?: string;
  hero_description?: string;
  show_category_filters?: boolean;
  empty_state_title?: string;
  empty_state_description?: string;
  show_cta_section?: boolean;
  cta_title?: string;
  cta_description?: string;
  cta_button_label?: string;
  cta_button_href?: string;
  detail_back_label?: string;
  detail_back_href?: string;
  detail_sidebar_author_label?: string;
  detail_sidebar_author_title?: string;
  detail_sidebar_author_subtitle?: string;
  show_detail_cta_section?: boolean;
  detail_cta_title?: string;
  detail_cta_description?: string;
  detail_cta_button_label?: string;
  detail_cta_button_href?: string;
  detail_related_eyebrow?: string;
  detail_related_heading?: string;
  detail_related_link_label?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface MarketUpdate {
  id: string;
  slug: string | null;
  status: string;
  market_calendar_day: string;
  title: string;
  indices_data?: unknown;
  top_gainers?: unknown;
  top_losers?: unknown;
  market_summary?: PortableTextBlock[];
  market_sentiment?: "Bullish" | "Bearish" | "Neutral" | "Volatile" | "Cautious";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface MarketUpdatesPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  page_subtitle?: string;
  show_trust_badges?: boolean;
  trust_badges?: unknown;
  latest_badge_label?: string;
  summary_section_title?: string;
  summary_section_icon?: string;
  sentiment_section_title?: string;
  sentiment_label?: string;
  gainers_section_title?: string;
  sentiment_icon?: string;
  losers_section_title?: string;
  gainers_view_all_label?: string;
  gainers_view_all_href?: string;
  losers_view_all_label?: string;
  losers_view_all_href?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface AdvisorPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  hero_badge?: string;
  hero_title?: string;
  hero_subtitle?: string;
  grid_section_title?: string;
  grid_section_intro?: string;
  show_trust_section?: boolean;
  trust_items?: unknown;
  specialties_section_heading?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  market_sentiment?: "Bullish" | "Bearish" | "Neutral" | "Volatile" | "Cautious";
  risk_level?: "Low" | "Medium" | "High" | "Very High";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  description?: PortableTextBlock[];
  icon?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  pricing_line?: string;
  duration?: string;
  feature_lines?: string;
  cta_text?: string;
  order?: number;
  is_recommended?: boolean;
  recommended_badge_label?: string;
  icon_symbol?: string;
  is_feature?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ServicePage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  hero_eyebrow?: string;
  hero_title?: string;
  hero_description?: string;
  show_bottom_cta?: boolean;
  bottom_cta_title?: string;
  bottom_cta_description?: string;
  bottom_cta_button_label?: string;
  bottom_cta_button_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  client_title?: string;
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  rating: number;
  service_used?: PortableTextBlock[];
  is_featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface TestimonialPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  hero_badge?: string;
  hero_title?: string;
  hero_description?: string;
  show_stats_section?: boolean;
  stats_background_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  stats_heading?: string;
  stats_subtitle?: string;
  stat_1_value?: string;
  stat_1_label?: string;
  stat_2_value?: string;
  stat_2_label?: string;
  stat_3_value?: string;
  stat_3_label?: string;
  show_partners_section?: boolean;
  partners_heading?: string;
  partner_logos?: unknown;
  show_cta_section?: boolean;
  cta_title?: string;
  cta_description?: string;
  cta_primary_label?: string;
  cta_primary_href?: string;
  cta_secondary_label?: string;
  cta_secondary_href?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    about_us: AboutUs;
    advisors: Advisor;
    book_consultation_page: BookConsultationPage;
    book_consultation_submissions: BookConsultationSubmission;
    contact_page: ContactPage;
    contact_submissions: ContactFormSubmission;
    faq_page: FaqPage;
    faqs: Faq;
    home_page: Home;
    investment_articles_page: InvestmentArticlesPage;
    market_updates: MarketUpdate;
    market_updates_page: MarketUpdatesPage;
    our_advisors_page: AdvisorPage;
    pages: Page;
    posts: Post;
    services: Service;
    services_page: ServicePage;
    testimonials: Testimonial;
    testimonials_page: TestimonialPage;
  }
}